### ISSUE TITLE
requirement subprocess error when installing via pip

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/bids_neuropoly#7]
I cloned the repo & run `pip install -e .`

Here is my terminal output:

```
alex-macbook:~/Desktop/bids_neuropoly $ pip install -e .
Obtaining file:///Users/alfoi/Desktop/bids_neuropoly
Requirement already satisfied: pybids>=0.6.5 in /Users/alfoi/anaconda2/lib/python2.7/site-packages (from bids-neuropoly==0.1) (0.6.5)
Requirement already satisfied: nibabel>=2.3.0 in /Users/alfoi/anaconda2/lib/python2.7/site-packages (from bids-neuropoly==0.1) (2.3.0)
Requirement already satisfied: pandas>=0.23.0 in /Users/alfoi/anaconda2/lib/python2.7/site-packages (from bids-neuropoly==0.1) (0.23.0)
Requirement already satisfied: gitpython in /Users/alfoi/anaconda2/lib/python2.7/site-packages (from bids-neuropoly==0.1) (2.1.11)
Collecting logging (from bids-neuropoly==0.1)
  Downloading https://files.pythonhosted.org/packages/93/4b/979db9e44be09f71e85c9c8cfc42f258adfb7d93ce01deed2788b2948919/logging-0.4.9.6.tar.gz (96kB)
    100% |████████████████████████████████| 102kB 3.8MB/s 
Collecting subprocess (from bids-neuropoly==0.1)
  Could not find a version that satisfies the requirement subprocess (from bids-neuropoly==0.1) (from versions: )
No matching distribution found for subprocess (from bids-neuropoly==0.1)
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by alexfoias** [comment]
subprocess is a standard module in Python 2.7. It's not necessary to add it in `requirements.txt`

**Comment by alexfoias** [comment]
@perone Since I closed the previous issue concerning git requirement. You were suggesting to separate the requirements for the API & convert script, since they have different requirements.

Would it be something like:
`pip install -e . -r requirements/api.txt`, 
`pip install -e . -r requirements/convert.txt` ? 

@jcohenadad what do you think about splitting the requirements ?

**Comment by jcohenadad** [comment]
> subprocess is a standard module in Python 2.7. It's not necessary to add it in requirements.txt

how about with py3.x?

**Comment by jcohenadad** [comment]
> @jcohenadad what do you think about splitting the requirements ?

i'm ok with it if the README is clear enough

**Comment by perone** [comment]
> Would it be something like:
> `pip install -e . -r requirements/api.txt`,
> `pip install -e . -r requirements/convert.txt` ?

So, I think there are three ways of doing this. The `bids_neuropoly` is a Python package where you have `setup.py` that allows you to install it, upload to PyPI, etc. The other folder, `script` isn't a Python package but a Python module without the Python installation procedure.

What can be done is:
1) Integrate this script inside the `bids_neuropoly` package. This would involve adding the script into the package, refactoring it to support being called by the setup script and then adding a new entry in the setup script to point that this script will be installed with that name and will be available in the path.
2) Just keep them separate and add a new `requirements.txt` inside the `scripts` folder that will then be installed as: `pip install -r scripts/requirements.txt`
3) Creating a setup.py, python package, etc, for the scripts.

I personally prefer the options 2 or 3, because it involves less work and keep a clear separation of concerns. Otherwise people from mila for instance, will have to install all dependencies of scripts without requiring it for the API.

**Comment by jcohenadad** [comment]
ok let's go with option 2 then-- seems like it's the easiest
